# An Ansible playbook that configures a Generic Cloud (Cloud-init) image
---
- name: AlmaLinux OS Generic Cloud Image
  hosts: all
  become: true

  roles:
    - role: unified_boot
      when: is_unified_boot is defined
    - xen_guest
    - cleanup_vm
